---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appbundle-project-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The app bundle POC project

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  # - namespace: "sampleapp1"
  #   server: "https://kubernetes.default.svc"
  # - namespace: "argocd"
  #   server: "https://kubernetes.default.svc"

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: appbundle
spec:
  destination:
    namespace: appbundle
    server: "https://kubernetes.default.svc"
  project: appbundle-project-dev
  source:
    path: argocd/apps-children/dev
    repoURL: https://github.com/d0-labs/argocd-app-of-apps-parent
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true