---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservicesdemo-istio
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: microservicesdemo
spec:
  project: microservicesdemo
  source:
    repoURL: "git@github.com:shrapk2/microservices-demo.git"
    targetRevision: HEAD
    path: release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: microservicesdemo
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
